---
- hosts: "{{ variable_host | default('all') }}"
  tasks:
    - name: Restarting ntpd Services
      service: name=ntpd state=restarted
    - name: Restarting ntp Services
      service: name=ntp state=restarted
